### ISSUE TITLE
LabelNew throws panic

### ISSUE THREAD

**Issue by edwardmp** [gotk3/gotk3#102]
LabelNew throws a panic here on Mac OS X El Capitan

```
(process:42530): GLib-GObject-CRITICAL **: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed

(process:42530): GLib-GObject-CRITICAL **: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x5389d71]

runtime stack:
runtime.throw(0x46681e0, 0x2a)
    /usr/local/Cellar/go/1.5.3/libexec/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
    /usr/local/Cellar/go/1.5.3/libexec/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x42b84a0, 0xc8200d9378, 0x0)
    /usr/local/Cellar/go/1.5.3/libexec/src/runtime/cgocall.go:120 +0x11b fp=0xc8200d9348 sp=0xc8200d9318
github.com/gotk3/gotk3/gtk._Cfunc_gtk_label_new(0x5f00060, 0x0)
    ??:0 +0x36 fp=0xc8200d9378 sp=0xc8200d9348
github.com/gotk3/gotk3/gtk.LabelNew(0x45a1910, 0x4, 0x0, 0x0, 0x0)
    /Users/Edward/Dropbox/Studie/2015-2016/Blok4/SoftwareConstruction/multi-ql/EdwardPoot/src/github.com/gotk3/gotk3/gtk/label.go:49 +0x82 fp=0xc8200d93b0 sp=0xc8200d9378
ql/gui.CreateLabel(0xc82009c0e1, 0x1d, 0x50)
```

**Comment by olabini** [comment]
Is this something that always happens? Are you running the code from the glib thread?

**Comment by andre-hub** [comment]
Closed, because of (current) relevance
