### ISSUE TITLE
cgo blows up with runtime error: `cgo argument has Go pointer to Go pointer` 

### ISSUE THREAD

**Issue by paultag** [gotk3/gotk3#142]
Go 1.6 has some more strict checking on what you can and can't do with Go pointers --

```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running, locked to thread]:
panic(0x65d200, 0xc4200185f0)
    /usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/sourcegraph/go-webkit2/webkit2.(*WebView).RunJavaScript(0xc420018530, 0xc4200595d8, 0xf, 0xc4200185e0)
    /home/paultag/.goenvs/epson/src/github.com/sourcegraph/go-webkit2/webkit2/webview.go:147 +0xea
main.main.func3(0xc4200380b8, 0x3)
    /home/paultag/dev/local/go-webkit2/cmd/webkit-eval-js/evaljs.go:84 +0xfb
reflect.Value.call(0x650f40, 0xc42000c5a0, 0x13, 0x6aeb1c, 0x4, 0xc42000c7b0, 0x2, 0x2, 0x0, 0x6490c0, ...)
    /usr/lib/go-1.7/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x650f40, 0xc42000c5a0, 0x13, 0xc42000c7b0, 0x2, 0x2, 0xc4200185d0, 0x82, 0x0)
    /usr/lib/go-1.7/src/reflect/value.go:302 +0xa4
github.com/gotk3/gotk3/glib.goMarshal(0x16b2180, 0x0, 0x2, 0x7ffe3a989690, 0x7ffe3a989610, 0x0)
    /home/paultag/.goenvs/epson/src/github.com/gotk3/gotk3/glib/glib.go:283 +0x601
github.com/gotk3/gotk3/glib._cgoexpwrap_cca433d51eec_goMarshal(0x16b2180, 0x0, 0x2, 0x7ffe3a989690, 0x7ffe3a989610, 0x0)
    ??:0 +0x5b
github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
    ??:0 +0x41
github.com/gotk3/gotk3/gtk.Main()
    /home/paultag/.goenvs/epson/src/github.com/gotk3/gotk3/gtk/gtk.go:766 +0x14
main.main()
    /home/paultag/dev/local/go-webkit2/cmd/webkit-eval-js/evaljs.go:93 +0x474
```

https://groups.google.com/forum/#!searchin/golang-nuts/cgo$20argument$20has$20Go$20pointer$20to$20Go$20pointer/golang-nuts/gnH0nhPf36I/4Shly3gxEwAJ

golang/go#12416

Design docs: https://github.com/golang/proposal/blob/master/design/12416-cgo-pointers.md

Originally reported as https://github.com/sourcegraph/go-webkit2/issues/33

**Comment by paultag** [comment]
Nevermind this is webkit. Sorry for the noise.
