### ISSUE TITLE
cgo argument has Go pointer to Go pointer when setting with GOGC=1

### ISSUE THREAD

**Issue by ugjka** [gotk3/gotk3#168]
I've battled this problem for a while, the solution was to use `glib.IdleAdd`
which seemed to work until today I tried to set the garbage collector to a minimal value `GOGC=1`
I don't know what I'm doing wrong at this point, any help would be appreciated.
[source](https://github.com/ugjka/newyearsbot)
```go
func (w *Status) addMessage(msg string) bool {
	w.buffer.Insert(w.iter, msg)
	if !w.iter.IsEnd() {
		w.iter.ForwardToEnd()
	}
	return false
}
```

```go
go func(s *Status) {
			for {
				var logmsg string
				select {
				case <-s.logStopper:
					return
				case logmsg = <-bot.LogCh:
					_, err := glib.IdleAdd(s.addMessage, logmsg)
					fatal(err)
				}
			}
		}(&st)
```

```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/gotk3/gotk3/gtk.(*TextIter).IsEnd.func1(0xc42001a4b0, 0x1c6bd50)
        /home/ugjka/goworks/src/github.com/gotk3/gotk3/gtk/text_iter.go:186 +0x52
github.com/gotk3/gotk3/gtk.(*TextIter).IsEnd(0xc42001a4b0, 0xc42001a4b0)
        /home/ugjka/goworks/src/github.com/gotk3/gotk3/gtk/text_iter.go:186 +0x30
main.(*Status).addMessage(0xc42001a2d0, 0xc4201e8150, 0x2c, 0xc420014f90)
        /home/ugjka/goworks/src/github.com/ugjka/newyearsbot/gui/status.go:78 +0x5e
main.(*Status).(main.addMessage)-fm(0xc4201e8150, 0x2c, 0x0)
        /home/ugjka/goworks/src/github.com/ugjka/newyearsbot/gui/main.go:61 +0x3e
reflect.Value.call(0x8f22c0, 0xc42025be10, 0x13, 0x9a8a26, 0x4, 0xc42024a0a0, 0x1, 0x1, 0xc4201e40c0, 0x8e0140, ...)
        /usr/lib/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0x8f22c0, 0xc42025be10, 0x13, 0xc42024a0a0, 0x1, 0x1, 0x4b8001, 0x10858e8, 0xc4200f3748)
        /usr/lib/go/src/reflect/value.go:302 +0xa4
github.com/gotk3/gotk3/glib.sourceAttach.func2()
        /home/ugjka/goworks/src/github.com/gotk3/gotk3/glib/glib.go:311 +0x18c
reflect.Value.call(0x8d6300, 0xc42024c320, 0x13, 0x9a8a26, 0x4, 0x10858e8, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/lib/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0x8d6300, 0xc42024c320, 0x13, 0x10858e8, 0x0, 0x0, 0x0, 0x0, 0x4609cf)
        /usr/lib/go/src/reflect/value.go:302 +0xa4
github.com/gotk3/gotk3/glib.goMarshal(0x7fb378001150, 0x7ffc3277e060, 0x0, 0x0, 0x0, 0x0)
        /home/ugjka/goworks/src/github.com/gotk3/gotk3/glib/glib.go:216 +0x5ba
github.com/gotk3/gotk3/glib._cgoexpwrap_e280e468d867_goMarshal(0x7fb378001150, 0x7ffc3277e060, 0x0, 0x0, 0x0, 0x0)
        github.com/gotk3/gotk3/glib/_obj/_cgo_gotypes.go:3561 +0x5b
github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
        github.com/gotk3/gotk3/gtk/_obj/_cgo_gotypes.go:11253 +0x41
github.com/gotk3/gotk3/gtk.Main()
        /home/ugjka/goworks/src/github.com/gotk3/gotk3/gtk/gtk.go:874 +0x20
main.main()
        /home/ugjka/goworks/src/github.com/ugjka/newyearsbot/gui/main.go:69 +0x2dd
exit status 2
```

**Comment by ugjka** [comment]
I tried to mix things up mutexes and what not it seems this method fails all the time 
`w.iter.IsEnd()` which is *gtk.TextIter

**Comment by ugjka** [comment]
I wonder if this a bug with go itself, because with default GOGC I can print status messages using the same code at insane rate (a message every 50 milliseconds)

**Comment by ugjka** [comment]
go version go1.8.1 linux/amd64

Name            : gtk3
Version         : 3.22.10-1

Name            : glib2
Version         : 2.50.3-1

**Comment by ugjka** [comment]
Closing, I cannot replicate the issue with the newest updates in this package and go
