### ISSUE TITLE
os.Exit(application.Run(os.Args)) causes a panic

### ISSUE THREAD

**Issue by russel** [gotk3/gotk3#264]
Coming back to a bit of Go code untouched for a long while… I updated the GoGTK3 library with `go get -u github.com/gotk3/gotk3/gtk` and then ran the code – it's just a trivial hello world button. The `main` function ends with:
```go
os.Exit(application.Run(os.Args))
```
but this throws an exception:
```
panic: reflect.Value.Convert: value of type *gtk.ApplicationWindow cannot be converted to type *gtk.Window

goroutine 1 [running]:
reflect.Value.Convert(0x7b9ae0, 0xc42009c4e0, 0x16, 0x7de4a0, 0x7b6ea0, 0x1, 0x0, 0x0)
	/usr/lib/go-1.10/src/reflect/value.go:2247 +0x250
github.com/gotk3/gotk3/glib.goMarshal(0x2ade3b0, 0x0, 0xc400000001, 0x7ffe21771840, 0x7ffe217717c0, 0x0)
	/home/users/russel/Built/Go/Dependencies/src/github.com/gotk3/gotk3/glib/glib.go:205 +0x309
github.com/gotk3/gotk3/glib._cgoexpwrap_90f29244dc17_goMarshal(0x2ade3b0, 0x0, 0x1, 0x7ffe21771840, 0x7ffe217717c0, 0x0)
	_cgo_gotypes.go:4246 +0x5b
github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x294c140, 0x1, 0x294de30, 0x0)
	_cgo_gotypes.go:1214 +0x4d
github.com/gotk3/gotk3/glib.(*Application).Run.func4(0x294c140, 0x1, 0x294de30, 0x0)
	/home/users/russel/Built/Go/Dependencies/src/github.com/gotk3/gotk3/glib/application.go:203 +0x97
github.com/gotk3/gotk3/glib.(*Application).Run(0xc42009c2d0, 0xc4200101b0, 0x1, 0x1, 0x0)
	/home/users/russel/Built/Go/Dependencies/src/github.com/gotk3/gotk3/glib/application.go:203 +0x134
main.main()
	/home/users/russel/Built/Go/Russel/src/helloWorld_gotk3_button/main.go:35 +0x140
```
Any thoughts as to whether this is a problem in my code (likely) or in gotk3 (less likely).

**Comment by andre-hub** [comment]
we probably had some broken source code places in the master at that time. If the error still exists, please reopen the ticket.
