### ISSUE TITLE
hi, can't get dnd working right.

### ISSUE THREAD

**Issue by hfmrow** [gotk3/gotk3#343]
Hi,
**I'm trying to work with drag and drop functionality but,
i allways get uintptr error conversion.**

*I've made this simple code for test purpose:*
```
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/gotk3/gotk3/gdk"
	"github.com/gotk3/gotk3/gtk"
)

func main() {
	// label "connect" receive data handler
	var destInData = func(lbi *gtk.Label,
		context *gdk.DragContext,
		x, y int,
		data *gtk.SelectionData,
		info, time uint) {
		fmt.Printf("%v\n", string(data.GetData()))
	}
	// Init gtk window
	gtk.Init(&os.Args)
	window, err := gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
	if err != nil {
		log.Fatal(err)
	}
	window.SetTitle("test DND")
	window.Connect("destroy", gtk.MainQuit)
	// Make vbox
	vbox, err := gtk.BoxNew(gtk.ORIENTATION_VERTICAL, 1)
	if err != nil {
		log.Fatal(err)
	}
	// Make label
	lblDest, err := gtk.LabelNew("dnd In")
	if err != nil {
		log.Fatal(err)
	}
	lblDest.Connect("drag-data-received", destInData)
	// Build dnd context
	var targets []gtk.TargetEntry
	te, err := gtk.TargetEntryNew("text/uri-list", gtk.TARGET_OTHER_APP, 0)
	if err != nil {
		log.Fatal(err)
	}
	targets = append(targets, *te)
	lblDest.DragDestSet(
		gtk.DEST_DEFAULT_ALL,
		targets,
		gdk.ACTION_COPY)
	// Pack all and display
	vbox.PackStart(lblDest, true, true, 0)
	window.Add(vbox)
	window.SetSizeRequest(300, 100)
	window.ShowAll()
	gtk.Main()
}
```
all look like good until i drop a file from "thunar" or other file explorer ...

```
panic: reflect.Value.Convert: value of type uintptr cannot be converted to type *gtk.SelectionData

goroutine 1 [running]:
reflect.Value.Convert(0x751b00, 0xc00001c218, 0x8c, 0x835fa0, 0x771d60, 0x751180, 0xc00001c210, 0x82)
	/usr/local/go/src/reflect/value.go:2351 +0x224
github.com/gotk3/gotk3/glib.goMarshal(0x1bc1300, 0x0, 0x7, 0x7ffd2ec99d70, 0x7ffd2ec99cf0, 0x0)
	/media/syndicate/storage/Documents/dev/go/src/github.com/gotk3/gotk3/glib/glib.go:205 +0x33e
github.com/gotk3/gotk3/glib._cgoexpwrap_29b5f1dca233_goMarshal(0x1bc1300, 0x0, 0x100000007, 0x7ffd2ec99d70, 0x7ffd2ec99cf0, 0x0)
	_cgo_gotypes.go:4250 +0x5b
github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
	_cgo_gotypes.go:13621 +0x41
github.com/gotk3/gotk3/gtk.Main(...)
	/media/syndicate/storage/Documents/dev/go/src/github.com/gotk3/gotk3/gtk/gtk.go:943
main.main()
	/media/syndicate/storage/Documents/dev/go/src/github.com/hfmrow/sandbox/GUI/main.go:56 +0x42e
```
If someone with a big heart and a little patience can explain why this error occur and eventually how to solve it.
i will give him a lot of thanks

Thank in advance ..

I'm working on:
LinuxMint 18.3, gtk-version: libgtk-3-0:amd64 3.18.9-1ubuntu3.3
release: xenial 45~16.04.1-Ubuntu SMP Mon Nov 19 13:02:27 UTC 2018
kernel: 4.15.0-46-generic x86_64
last gotk3 re-compiled for 3.18 (on wednesday6) and golang v1.12.

**Comment by SilentGopherLnx** [comment]
Use this:
	
var destInData = func(lbi *gtk.Label,
		context *gdk.DragContext,
		x, y int,
		data_ptr uintptr,
		info, time uint) {
		data := gtk.GetData(data_ptr)
		fmt.Printf("%v\n", string(data))
	}

**Comment by hfmrow** [comment]
@SilentGopherLnx 
Thanks a thousand times, 
this one work perfect.

**Comment by jl6** [comment]
Just in case this helps anyone else... I'm learning go and gotk3 and I managed to get this to work using the code originally posted by hfmrow.
