### ISSUE TITLE
OS X Installation page out of date

### ISSUE THREAD

**Issue by mikeweilgart** [gotk3/gotk3#377]
The page at https://github.com/gotk3/gotk3/wiki/Installing-on-OSX is out of date.

Firstly, the name of the script has changed; it's now https://gitlab.gnome.org/GNOME/gtk-osx/raw/master/gtk-osx-setup.sh

Secondly, the `jhbuild` alias is wrong; it should now be `alias jhbuild="PATH=$HOME/gtk/bin:$PATH ~/.new_local/bin/jhbuild"`

But more importantly, even with those changes, the installation procedure doesn't work for me; on Mac OS X 10.11.6, I get the following:

```
Installing CPython 3.6.8 with pyenv (this may take a few minutes)…
Traceback (most recent call last):
  File "/Users/Mike/.new_local/bin/pipenv", line 10, in <module>
    sys.exit(cli())
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/cli/command.py", line 249, in install
    editable_packages=state.installstate.editables,
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/core.py", line 1695, in do_install
    pypi_mirror=pypi_mirror,
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/core.py", line 561, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/core.py", line 484, in ensure_virtualenv
    python = ensure_python(three=three, python=python)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/core.py", line 447, in ensure_python
    c = pyenv.install(version)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/pyenv.py", line 117, in install
    timeout=PIPENV_INSTALL_TIMEOUT,
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/pyenv.py", line 73, in _pyenv
    raise PyenvError('faild to run {0}'.format(args), c)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/pyenv.py", line 56, in __init__
    self.err = c.err
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/delegator.py", line 146, in err
    return self._pexpect_out
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/delegator.py", line 114, in _pexpect_out
    result += self.subprocess.after
TypeError: coercing to Unicode: need string or buffer, type found
/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/vistir/compat.py:109: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/var/folders/lm/mw4dy58s4y5cnxxg5m25zgmm0000gn/T/pipenv-kMb9Dm-requirements'>
  warnings.warn(warn_message, ResourceWarning)
Installing jhbuild configuration at /Users/Mike/.config/jhbuildrc
Installing jhbuild custom configuration at /Users/Mike/.config/jhbuildrc-custom
```

Then a similar error when attempting the jhbuild bootstrap:

```
$ alias jhbuild="PATH=$HOME/gtk/bin:$PATH ~/.new_local/bin/jhbuild"
$ jhbuild bootstrap
Warning: Python 3.6 was not found on your system…
Traceback (most recent call last):
  File "/Users/Mike/.new_local/bin/pipenv", line 10, in <module>
    sys.exit(cli())
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/cli/command.py", line 396, in run
    command=command, args=args, three=state.three, python=state.python, pypi_mirror=state.pypi_mirror
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/core.py", line 2191, in do_run
    ensure_project(three=three, python=python, validate=False, pypi_mirror=pypi_mirror)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/core.py", line 561, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/core.py", line 484, in ensure_virtualenv
    python = ensure_python(three=three, python=python)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/core.py", line 419, in ensure_python
    version = pyenv.find_version_to_install(python)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/pyenv.py", line 99, in find_version_to_install
    ), key=operator.attrgetter('cmpkey'))
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/pyenv.py", line 96, in <genexpr>
    inst_version
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/pyenv.py", line 79, in iter_installable_versions
    for name in self._pyenv('install', '--list').out.splitlines():
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/pyenv.py", line 73, in _pyenv
    raise PyenvError('faild to run {0}'.format(args), c)
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/pyenv.py", line 56, in __init__
    self.err = c.err
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/delegator.py", line 146, in err
    return self._pexpect_out
  File "/Users/Mike/.new_local/lib/python/site-packages/pipenv/vendor/delegator.py", line 114, in _pexpect_out
    result += self.subprocess.after
TypeError: coercing to Unicode: need string or buffer, type found
```

I am not sure what all changes need to be made to the installation instructions for them to work.  Possibly I can work through these myself and if so, I'll update the wiki accordingly.  But the first step is documenting that there's an issue.  (It may be a few days before I get back to this.)

**Comment by mikeweilgart** [comment]
It looks like the Python installation failed; what I'm going to try next is installing the latest Python3 from the Python website, and then re-try the script.  Since the script tried the Python 3 installation itself, though (after prompting me), there is probably a bug there that should be traced down.

**Comment by mikeweilgart** [comment]
Also see https://gitlab.gnome.org/GNOME/gtk-osx/issues/6

**Comment by Bios-Marcel** [comment]
Hey, I don't know which of the team members use OSX. At least I don't use it, so I can't really solve this. If you manage to figure out everything, it'd be awesome if you could update the wiki page.

**Comment by pojntfx** [comment]
As someone who uses a Mac from time to time, I've just updated the docs for support of the latest macOS Catalina: https://github.com/gotk3/gotk3/wiki/Installing-on-macOS
