### ISSUE TITLE
[BUG] gtk.TreeModel GetValue function bug

### ISSUE THREAD

**Issue by mondy** [gotk3/gotk3#541]
**Describe the bug**
Panic occurs when adding more elements to gtk.ListStore with the following sources.
In my environment it doesn't happen with 50 elements. But it happens with 200 elements.
However, there are times when it occurs with the same number of elements, and sometimes not.
I'm sorry if you mistake how to using this library.

**To Reproduce**
Execute this code.
If not occurs, add more elements.
The same occurs for string column.

```go
package main

import (
	"fmt"

	"github.com/gotk3/gotk3/glib"
	"github.com/gotk3/gotk3/gtk"
)

const (
	stringColumn = iota
	int64Column
)

func main() {
	list, err := gtk.ListStoreNew(
		glib.TYPE_STRING,
		glib.TYPE_INT64,
	)
	if err != nil {
		return
	}
	// list.SetSortFunc(stringColumn, func(model *gtk.TreeModel, i, j *gtk.TreeIter, _ interface{}) int {
	// 	return strings.Compare(getStringValue(model, i), getStringValue(model, j))
	// })
	// list.SetSortColumnId(stringColumn, gtk.SORT_DESCENDING)

	list.SetSortFunc(int64Column, func(model *gtk.TreeModel, i, j *gtk.TreeIter, _ interface{}) int {
		return int(getInt64Value(model, i) - getInt64Value(model, j))
	})
	list.SetSortColumnId(int64Column, gtk.SORT_ASCENDING)

	for i := 0; i < 200; i++ {
		addValue(list, fmt.Sprintf("%04d", i), int64(i))
	}
}

func getStringValue(model *gtk.TreeModel, i *gtk.TreeIter) string {
	value, _ := model.GetValue(i, stringColumn)
	str, _ := value.GetString()
	return str
}

func getInt64Value(model *gtk.TreeModel, i *gtk.TreeIter) int64 {
	value, _ := model.GetValue(i, int64Column)
	v, _ := value.GoValue()
	return v.(int64)
}

func addValue(list *gtk.ListStore, name string, value int64) {
	iter := list.Append()
	list.Set(iter, []int{
		stringColumn,
		int64Column,
	}, []interface{}{
		name,
		value,
	})
}
```

**Expected behavior**
No error message is output.

**Error messages**
```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/gotk3/gotk3/gtk.(*TreeModel).GetValue.func1(0xc000103770, 0xc00010b000, 0x1, 0xc000103778)
        /home/username/.go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/gtk/gtk.go:9210 +0x93
github.com/gotk3/gotk3/gtk.(*TreeModel).GetValue(0xc000103770, 0xc00010b000, 0x1, 0x7ee260, 0xc0000a7af8, 0x537fa8)
        /home/username/.go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/gtk/gtk.go:9210 +0x82
main.getInt64Value(0xc000103770, 0xc00010b000, 0x22b5001)
        /home/username/repos/gotk3bug/main.go:45 +0x42
main.main.func1(0xc000103770, 0xc00010b000, 0xc00010b020, 0x0, 0x0, 0x1)
        /home/username/repos/gotk3bug/main.go:29 +0x35
github.com/gotk3/gotk3/gtk.goTreeSortableSortFuncs(0x22b5090, 0x7ffe8f088790, 0x7ffe8f0887b0, 0x1, 0x0)
        /home/username/.go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/gtk/gtk_export.go:132 +0x19a
github.com/gotk3/gotk3/gtk._cgoexpwrap_d60e5f3c4773_goTreeSortableSortFuncs(0x22b5090, 0x7ffe8f088790, 0x7ffe8f0887b0, 0x1, 0x7ffe8f088760)
        _cgo_gotypes.go:34619 +0x49
github.com/gotk3/gotk3/gtk._Cfunc_gtk_list_store_set_value(0x22b5090, 0xc00010ada0, 0x1, 0x22ec3d0)
        _cgo_gotypes.go:15263 +0x45
github.com/gotk3/gotk3/gtk.(*ListStore).SetValue.func2(0xc00000e0c0, 0xc00010ada0, 0x1, 0xc000103760)
        /home/username/.go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/gtk/gtk.go:5340 +0xbe
github.com/gotk3/gotk3/gtk.(*ListStore).SetValue(0xc00000e0c0, 0xc00010ada0, 0x1, 0x7b0ac0, 0xc000100870, 0x0, 0x0)
        /home/username/.go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/gtk/gtk.go:5340 +0xcc
github.com/gotk3/gotk3/gtk.(*ListStore).Set(0xc00000e0c0, 0xc00010ada0, 0xc0000a7eb8, 0x2, 0x2, 0xc0000a7ed0, 0x2, 0x2, 0xc000106000, 0xc000100028)
        /home/username/.go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/gtk/gtk.go:5320 +0x98
main.addValue(0xc00000e0c0, 0xc000100868, 0x4, 0x74)
        /home/username/repos/gotk3bug/main.go:52 +0x116
main.main()
        /home/username/repos/gotk3bug/main.go:34 +0x15f
exit status 2
```
**Environment:**
gtk3 version: 3.22.30-1ubuntu4
gotk3 version: v0.4.0
go version: 1.14 linux/amd64
os: Ubuntu 18.04

**Comment by MJacred** [comment]
Hi, thanks for reporting this bug.

Can you tell me on which commit your build is based on? Latest commit on master? Some release version?

**Comment by mondy** [comment]
gotk3 version is v0.4.0
I checked go.mod file.
```
module repos/gotk3bug

go 1.14

require github.com/gotk3/gotk3 v0.4.0
```
Is this the information you are looking for?

**Comment by MJacred** [comment]
yes, thank you.

I'll probably check this on Monday.

**Comment by MJacred** [comment]
OK, I tested on v0.4.0 as well.

I have the same specs as you, except my go version is: go1.13.3 linux/amd64

And it works for me. Tested with 20000000000 elements

go 1.14 made some breaking changes to cgo -> https://golang.org/doc/go1.4:
* https://golang.org/doc/go1.4#methodonpointertopointer
* https://golang.org/doc/go1.4#gocmd

You might want to use go 1.13 in the meantime

**Comment by mondy** [comment]
Thank you for testing.
I tried following golang versions.
But following versions return error message.

* 1.13.9 (installed by snap)
* 1.12.17 (installed by snap)
* 1.13.3 (installed by offical)

I don't know what to do..

By the way, what is the version of gcc?
My gcc is `gcc (Ubuntu 8.3.0-26ubuntu1~18.04) 8.3.0`.

**Comment by MJacred** [comment]
My gcc is gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by mondy** [comment]
Thank you for your reply.
I tried following environment, but return error message.
* `gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0`
* `go1.13.3 linux/amd64`

**Comment by MJacred** [comment]
I removed two unnecessary casts for `GetValue()` in this branch: https://github.com/cubiest/gotk3/tree/treemodel/getvalue_cast

Could you try it with this, please?

**Comment by mondy** [comment]
Thanks.
I tried https://github.com/cubiest/gotk3/tree/treemodel/getvalue_cast, but return error message.

**Comment by MJacred** [comment]
ok... @founderio also found a potential issue. Value.Native() did not return a `uintptr`.  
I fixed that, so please test again with the most recent commit from the same branch

**Comment by mondy** [comment]
I tried, but return error message.

I tried following environment.
* gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
* go1.13.3 linux/amd64

Clone `github.com/cubiest/gotk3` from  `treemodel/getvalue_cast` branch to ` /path/to/repos/github.com/cubiest/gotk3`.

go.mod file is following.
```
module repos/gotk3bug

replace github.com/gotk3/gotk3 => /path/to/repos/github.com/cubiest/gotk3

go 1.13

require github.com/gotk3/gotk3 v0.0.0-00010101000000-000000000000
```

**Comment by MJacred** [comment]
the go mod command you need to execute should look like this:

```go
go mod edit -replace github.com/gotk3/gotk3=github.com/cubiest/gotk3@ddf2b2f75be64c04e0d2dcf042ac07c2496e55b0
```

then your go.mod file should have this line
```
replace github.com/gotk3/gotk3 => github.com/cubiest/gotk3 v0.0.0-20200328092210-ddf2b2f75be6
```

you don't need to clone our repository

**Comment by mondy** [comment]
Thank you for the information.
I tried, but return error message.

**Comment by MJacred** [comment]
please try again with the newest commit in  treemodel/getvalue_cast.

It should output something like this for each call of `GetValue()`:

```
2000
value: *glib.Value, &glib.Value{GValue:(*glib._Ctype_struct__GValue)(0x2a88720)}
native: *glib.Value, &glib.Value{GValue:(*glib._Ctype_struct__GValue)(0x2a88720)}
pointer: *glib.Value, &glib.Value{GValue:(*glib._Ctype_struct__GValue)(0x2a88720)}
casted: *glib.Value, &glib.Value{GValue:(*glib._Ctype_struct__GValue)(0x2a88720)}
```

please create a global integer counter.  
add `log.Println(counter)` before you call the `GetValue()` func.  
and afterwards, so that it counts up each time  `value, _ := model.GetValue(i, int64Column)` got called

after running your program, please print your terminal output for the last 5 rows before the crash occurs. So we can see what your program has in cache before it crashes

before you write back, please also try again while removing the line `runtime.GC()` to see if it still crashes

**Comment by mondy** [comment]
Sorry for the late reply.
I tried it.

```
2020/04/30 21:20:03 214
2020/04/30 21:20:03 value: *glib.Value, &glib.Value{GValue:(*glib._Ctype_struct__GValue)(0x1c49460)}
2020/04/30 21:20:03 native: *glib.Value, &glib.Value{GValue:(*glib._Ctype_struct__GValue)(0x1c49460)}
2020/04/30 21:20:03 pointer: *glib.Value, &glib.Value{GValue:(*glib._Ctype_struct__GValue)(0x1c49460)}
2020/04/30 21:20:03 casted: *glib.Value, &glib.Value{GValue:(*glib._Ctype_struct__GValue)(0x1c49460)}
panic: runtime error: cgo argument has Go pointer to Go pointer
```

> before you write back, please also try again while removing the line runtime.GC() to see if it still crashes

I couldn't find runtime.GC().
Where should I remove runtime.GC()?

**Comment by MJacred** [comment]
hm... I had `runtime.GC()` in my code - wanted to check sth. Sorry about that.

Anyway, I could reproduce your error when running the code over and over again (happens around 1 out of 10 times). The issue is that **the cgo rules got stricter** with Go 1.6: https://github.com/golang/go/issues/12416

**so there will be problems at other parts of the code...**

here is a repo which **helps to fix it**: https://github.com/mattn/go-pointer  

example in the other go-wrapper repo for gtk: https://github.com/mattn/go-gtk/blob/af2e013261f57706ec683a61f85e8759a3faf6be/gtk/gtk.go#L4915-L4930

now is the question on whether we should use the **Gopkg.lock or go.mod**? Latter kills support of Go <v1.11. Any opinions? @andre-hub  @founderio

**Comment by andre-hub** [comment]
@MJacred 

We should integrate the solution with the go-pointers into the project. I didn't see that until now, but it makes sense to use it.

go.mod is currently the preferred variant.

We are now trying a two-track development. For Go <v1.11 the 0.5 branch will remain, for newer golang versions the 0.6

**Comment by founderio** [comment]
Sounds like a useful library. Although that smells like an awful hack to me :D  
As long as we think about when .Unref() is called, did not find that in their code, but I also did not check thoroughly. Just want to avoid memory leaks. We already have enough of those (presumably).

@andre-hub Do you expect incompatibilities to older Go versions? They should just ignore the go.mod file and reference the "latest" version as usual, right?  
Other dependency managers should also pick up the version tags as usual.

**Comment by andre-hub** [comment]
@founderio 

there used to be memory leaks by default.
but i didn't get that deep into the latest versions of GO and the connection of cgo and i don't know in detail if it has improved. 

see old issue from 2014 : https://github.com/conformal/gotk3/issues/86#issuecomment-60388133
and https://github.com/conformal/gotk3/issues/55

i expect incompatibilities in the near future, simply because many of versions of libraries are depicted here. Currently there are 6 supported GO versions and around 9 gtk versions.
