### ISSUE TITLE
[Project question] How to store arbitrary Go variables to TreeStore or ListStore?

### ISSUE THREAD

**Issue by linuxerwang** [gotk3/gotk3#575]
I need to let the TreeStore and ListStore to hold some Go variables (pointer to a complicated Go struct which contains pointer to deep level of other structs). The store is defined to have a GObject column type (through Glade), and at present it gives me the error like:

panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/gotk3/gotk3/glib.(*Value).SetPointer.func1(0xc000010180, 0xc000010168)
        /home/ubuntu/go/src/github.com/gotk3/gotk3/glib/glib.go:1382 +0x51
github.com/gotk3/gotk3/glib.(*Value).SetPointer(0xc000010180, 0xc000010168)
        /home/ubuntu/go/src/github.com/gotk3/gotk3/glib/glib.go:1382 +0x35
github.com/gotk3/gotk3/glib.GValue(0x7d2da0, 0xc000010168, 0x1, 0xc000010178, 0x0)
        /home/ubuntu/go/src/github.com/gotk3/gotk3/glib/glib.go:1122 +0x4c9
github.com/gotk3/gotk3/gtk.(*ListStore).SetValue(0xc00000e0a0, 0xc00000e0e0, 0x2, 0x7d2da0, 0xc000010168, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/gotk3/gotk3/gtk/gtk.go:5406 +0x91
github.com/gotk3/gotk3/gtk.(*ListStore).Set(0xc00000e0a0, 0xc00000e0e0, 0xc000133eb8, 0x3, 0x3, 0xc000133f00, 0x3, 0x3, 0x78cae0, 0xc000133ed8)
        /home/ubuntu/go/src/github.com/gotk3/gotk3/gtk/gtk.go:5393 +0x98
main.addRow(0xc00000e0a0, 0x8974cc, 0x3, 0x8a0201, 0x33)
        /home/ubuntu/go/src/github.com/gotk3/gotk3-examples/gtk-examples/treeview/treeview.go:72 +0x1b6
main.main()
        /home/ubuntu/go/src/github.com/gotk3/gotk3-examples/gtk-examples/treeview/treeview.go:106 +0xbd

Thanks!

**Comment by MJacred** [comment]
you may want to have a look at https://github.com/mattn/go-pointer. Maybe you have to put this or sth. else into your own glib.Type object... We'll also look into this further in a month or two. If you find out, please share!

but giving a Go Pointer which contains more Go Pointers won't be possible due to cgo restrictions. Go and C sharing memory of each other is bad... That's why you got an `cgo argument has Go pointer to Go pointer` error

**Comment by linuxerwang** [comment]
Thanks, @MJacred. It's interesting. At present I solved the issue with a local map from id to the object, and only store the ids to liststore.

**Comment by MJacred** [comment]
Please close the issue, if your question is answered (reduces cluttering in the issue list)
