### ISSUE TITLE
[BUG] title

### ISSUE THREAD

**Issue by adrianboyko** [gotk3/gotk3#630]
**Describe the bug**
A simple program that repeatedly adds and removes rows from a list box crashes after a few minutes.

**To Reproduce**

```
package main

import (
	"github.com/gotk3/gotk3/glib"
	"github.com/gotk3/gotk3/gtk"
)

func main() {
	gtk.Init(nil)
	win, _ := gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
	box, _ := gtk.ListBoxNew()
	win.Add(box)
	win.SetDefaultSize(200, 900)
	win.ShowAll()
	glib.IdleAdd(testAddRows, box)
	gtk.Main()
}

func testAddRows(box *gtk.ListBox) bool {
	for i:=0; i<40; i++ {
		label, _ := gtk.LabelNew("SPAM")
		row, _ := gtk.ListBoxRowNew()
		row.Add(label)
		box.Add(row)
		label.Show()
		row.Show()
	}
	glib.IdleAdd(testDeleteRows, box)
	return false
}

func testDeleteRows(box *gtk.ListBox) bool {
	for {
		row := box.GetRowAtIndex(0)
		if row == nil {
			break
		}
		row.Destroy()
	}
	glib.IdleAdd(testAddRows, box)
	return false
}

```

**Expected behavior**

The program should run forever, alternately adding rows and then deleting them.

**Error messages**

```
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x62a5b60 pc=0x62a5b60]

runtime stack:
runtime.throw(0x8c211c, 0x2a)
        /usr/lib/go-1.13/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
        /usr/lib/go-1.13/src/runtime/signal_unix.go:378 +0x47c

goroutine 18 [syscall]:
runtime.cgocall(0x7989a0, 0xc00003c6d0, 0xc000000000)
        /usr/lib/go-1.13/src/runtime/cgocall.go:128 +0x5b fp=0xc00003c6a0 sp=0xc00003c668 pc=0x47b09b
github.com/gotk3/gotk3/glib._Cfunc_g_object_unref(0xa347db0)
        _cgo_gotypes.go:2967 +0x41 fp=0xc00003c6d0 sp=0xc00003c6a0 pc=0x539491
github.com/gotk3/gotk3/glib.(*Object).Unref.func1(0xc00034d148)
        /home/adrian/go/src/github.com/gotk3/gotk3/glib/glib.go:537 +0x5e fp=0xc00003c710 sp=0xc00003c6d0 pc=0x54c06e
github.com/gotk3/gotk3/glib.(*Object).Unref(0xc00034d148)
        /home/adrian/go/src/github.com/gotk3/gotk3/glib/glib.go:537 +0x2b fp=0xc00003c728 sp=0xc00003c710 pc=0x54112b
runtime.call32(0x0, 0x8c3928, 0xc00001e100, 0x1000000010)
        /usr/lib/go-1.13/src/runtime/asm_amd64.s:539 +0x3b fp=0xc00003c758 sp=0xc00003c728 pc=0x4cccfb
runtime.runfinq()
        /usr/lib/go-1.13/src/runtime/mfinal.go:222 +0x1df fp=0xc00003c7e0 sp=0xc00003c758 pc=0x48ee7f
runtime.goexit()
        /usr/lib/go-1.13/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00003c7e8 sp=0xc00003c7e0 pc=0x4cea11
created by runtime.createfing
        /usr/lib/go-1.13/src/runtime/mfinal.go:156 +0x61

goroutine 1 [syscall, locked to thread]:
github.com/gotk3/gotk3/gtk._Cfunc_gtk_widget_show(0x9f69f40)
        _cgo_gotypes.go:32367 +0x41 fp=0xc0000cf768 sp=0xc0000cf738 pc=0x5e1c21
github.com/gotk3/gotk3/gtk.(*Widget).Show.func1(0xc0002eaea0)
        /home/adrian/go/src/github.com/gotk3/gotk3/gtk/widget.go:216 +0x64 fp=0xc0000cf7a8 sp=0xc0000cf768 pc=0x68d464
github.com/gotk3/gotk3/gtk.(*Widget).Show(0xc0002eaea0)
        /home/adrian/go/src/github.com/gotk3/gotk3/gtk/widget.go:216 +0x2b fp=0xc0000cf7c0 sp=0xc0000cf7a8 pc=0x63577b
main.testAddRows(0xc0000a4108, 0x0)
        /home/adrian/go/src/awesomeProject/crash.go:26 +0xc3 fp=0xc0000cf838 sp=0xc0000cf7c0 pc=0x7971b3
reflect.Value.call(0x809ae0, 0x8c4658, 0x13, 0x8ba5f3, 0x4, 0xc000094280, 0x1, 0x1, 0x16, 0x4b7a0c, ...)
        /usr/lib/go-1.13/src/reflect/value.go:460 +0x5f6 fp=0xc0000cfa88 sp=0xc0000cf868 pc=0x4f2af6
reflect.Value.Call(0x809ae0, 0x8c4658, 0x13, 0xc000094280, 0x1, 0x1, 0xc0000a4108, 0x16, 0x1)
        /usr/lib/go-1.13/src/reflect/value.go:321 +0xb4 fp=0xc0000cfb08 sp=0xc0000cfa88 pc=0x4f22b4
github.com/gotk3/gotk3/glib.goMarshal(0x7649eb0, 0x7ffdbec57550, 0xc000000000, 0x0, 0x0, 0x0)
        /home/adrian/go/src/github.com/gotk3/gotk3/glib/glib.go:255 +0x700 fp=0xc0000cfc80 sp=0xc0000cfb08 pc=0x540390
github.com/gotk3/gotk3/glib._cgoexpwrap_3a432a83c3cf_goMarshal(0x7649eb0, 0x7ffdbec57550, 0x0, 0x0, 0x0, 0x0)
        _cgo_gotypes.go:5501 +0x5b fp=0xc0000cfcc0 sp=0xc0000cfc80 pc=0x53d18b
github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
        _cgo_gotypes.go:16679 +0x41 fp=0xc0000cfef0 sp=0xc0000cfec0 pc=0x5bbf41
github.com/gotk3/gotk3/gtk.Main(...)
        /home/adrian/go/src/github.com/gotk3/gotk3/gtk/gtk.go:1118
main.main()
        /home/adrian/go/src/awesomeProject/crash.go:16 +0xfe fp=0xc0000cff60 sp=0xc0000cfef0 pc=0x7970ce
[signal SIGSEGV: segmentation violation code=0x2 addr=0x62a5b60 pc=0x62a5b60]

runtime stack:
runtime.throw(0x8c211c, 0x2a)
        /usr/lib/go-1.13/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
        /usr/lib/go-1.13/src/runtime/signal_unix.go:378 +0x47c

```

**Environment:**
gtk3 version: '3.24.20-0ubuntu1'
go version: '1.13.8'
os: 'Ubuntu Mate 20.04'

 
**Additional context**
None

**Comment by hfmrow** [comment]
Hi,
your code runs for about 40 minutes without problem ...
How long to get stuck with a fatal error ?
| Name            | Version / Info / Name                          |
| --------------- | ---------------------------------------------- |
| GOLANG          | V1.14.6 -> GO111MODULE="off", GOPROXY="direct" |
| DISTRIB         | LinuxMint Xfce                                      |
| VERSION         | 20                                             |
| CODENAME        | CODENAME=ulyana                                |
| RELEASE         | #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020    |
| UBUNTU_CODENAME | focal                                          |
| KERNEL          | 5.4.0-42-generic                               |
| HDWPLATFORM     | x86_64                                         |
| GTK+ 3          | 3.24.20                                        |
| GLIB 2          | 2.64.3                                         |
| CAIRO           | 1.16.0                                         |

**Comment by adrianboyko** [comment]
Thanks for trying the code. It takes about 2 minutes to fail on my machine. Fails every run, without fail.

**Comment by hfmrow** [comment]
Ok, i can see the go version is not same as me, maybe you can try to update golang ... don't know if it will change anything but ... why not.

**Comment by adrianboyko** [comment]
Same result with 1.14.6.

**Comment by ryanerwin** [comment]
I'm running this under `go 1.13.8` on Ubuntu `20.04` and getting the same crash to happen in 4 minutes or less, however, note that this program **is using 100% of the CPU** while it's running. 

If rewritten to not hog the CPU, curious if the crash will still happen?

I looked at it with `strace -f`, but it could only narrow it down to the same SIGSEGV that we see in go.

Curious if the exact same program rewritten in C will also crash?

```
'go run ./listboxCrash.go' time: 4:07.54s, cpu: 103%
```

```
'go run ./listboxCrash.go' time: 2:27.64s, cpu: 104%
```

```
'go run ./listboxCrash.go' time: 49.701s, cpu: 107%
```

Running it under strace, I can get it to crash even faster...

```
'strace -f go run ./listboxCrash.go' time: 24.354s, cpu: 105%
```

<details>
<summary>go run ./listboxCrash.go error output</summary>

```
 ❯ go run ./listboxCrash.go
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x902da30 pc=0x902da30]

runtime stack:
runtime.throw(0x8c2118, 0x2a)
	/usr/lib/go-1.13/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/usr/lib/go-1.13/src/runtime/signal_unix.go:378 +0x47c

goroutine 18 [syscall]:
runtime.cgocall(0x7989c0, 0xc00003c6d0, 0xc000000000)
	/usr/lib/go-1.13/src/runtime/cgocall.go:128 +0x5b fp=0xc00003c6a0 sp=0xc00003c668 pc=0x47b0ab
github.com/gotk3/gotk3/glib._Cfunc_g_object_unref(0x6e9e400)
	_cgo_gotypes.go:2967 +0x41 fp=0xc00003c6d0 sp=0xc00003c6a0 pc=0x5394a1
github.com/gotk3/gotk3/glib.(*Object).Unref.func1(0xc0002be978)
	/home/ryan/go/pkg/mod/github.com/gotk3/gotk3@v0.4.1-0.20200722150342-c076f80955ab/glib/glib.go:537 +0x5e fp=0xc00003c710 sp=0xc00003c6d0 pc=0x54c07e
github.com/gotk3/gotk3/glib.(*Object).Unref(0xc0002be978)
	/home/ryan/go/pkg/mod/github.com/gotk3/gotk3@v0.4.1-0.20200722150342-c076f80955ab/glib/glib.go:537 +0x2b fp=0xc00003c728 sp=0xc00003c710 pc=0x54113b
runtime.call32(0x0, 0x8c3a00, 0xc00045a020, 0x1000000010)
	/usr/lib/go-1.13/src/runtime/asm_amd64.s:539 +0x3b fp=0xc00003c758 sp=0xc00003c728 pc=0x4ccd0b
runtime.runfinq()
	/usr/lib/go-1.13/src/runtime/mfinal.go:222 +0x1df fp=0xc00003c7e0 sp=0xc00003c758 pc=0x48ee8f
runtime.goexit()
	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00003c7e8 sp=0xc00003c7e0 pc=0x4cea21
created by runtime.createfing
	/usr/lib/go-1.13/src/runtime/mfinal.go:156 +0x61

goroutine 1 [runnable, locked to thread]:
github.com/gotk3/gotk3/glib._Cfunc_g_object_is_floating(0x27c65f0, 0x1)
	_cgo_gotypes.go:2913 +0x49
github.com/gotk3/gotk3/glib.(*Object).IsFloating.func1(0xc0004a2000, 0xc0004a2000)
	/home/ryan/go/pkg/mod/github.com/gotk3/gotk3@v0.4.1-0.20200722150342-c076f80955ab/glib/glib.go:547 +0x5e
github.com/gotk3/gotk3/glib.(*Object).IsFloating(0xc0004a2000, 0xc0004a2000)
	/home/ryan/go/pkg/mod/github.com/gotk3/gotk3@v0.4.1-0.20200722150342-c076f80955ab/glib/glib.go:547 +0x2b
github.com/gotk3/gotk3/glib.Take(0x27c65f0, 0xc00044c598)
	/home/ryan/go/pkg/mod/github.com/gotk3/gotk3@v0.4.1-0.20200722150342-c076f80955ab/glib/glib.go:497 +0x71
github.com/gotk3/gotk3/gtk.ListBoxRowNew(0x8c3702, 0x2, 0xc00044c5a8)
	/home/ryan/go/pkg/mod/github.com/gotk3/gotk3@v0.4.1-0.20200722150342-c076f80955ab/gtk/gtk_since_3_10.go:556 +0x32
main.testAddRows(0xc0000b0108, 0x0)
	/home/ryan/Dev/sshdoc/scratch/listboxCrash/listboxCrash.go:25 +0x66
reflect.Value.call(0x809ae0, 0x8c4730, 0x13, 0x8ba5f3, 0x4, 0xc00000e180, 0x1, 0x1, 0x16, 0x4b7a1c, ...)
	/usr/lib/go-1.13/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0x809ae0, 0x8c4730, 0x13, 0xc00000e180, 0x1, 0x1, 0xc0000b0108, 0x16, 0x1)
	/usr/lib/go-1.13/src/reflect/value.go:321 +0xb4
github.com/gotk3/gotk3/glib.goMarshal(0xabb1f60, 0x7ffeb88cb730, 0xc000000000, 0x0, 0x0, 0x0)
	/home/ryan/go/pkg/mod/github.com/gotk3/gotk3@v0.4.1-0.20200722150342-c076f80955ab/glib/glib.go:255 +0x700
github.com/gotk3/gotk3/glib._cgoexpwrap_3a432a83c3cf_goMarshal(0xabb1f60, 0x7ffeb88cb730, 0x0, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:5501 +0x5b
github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
	_cgo_gotypes.go:16680 +0x41
github.com/gotk3/gotk3/gtk.Main(...)
	/home/ryan/go/pkg/mod/github.com/gotk3/gotk3@v0.4.1-0.20200722150342-c076f80955ab/gtk/gtk.go:1118
main.main()
	/home/ryan/Dev/sshdoc/scratch/listboxCrash/listboxCrash.go:18 +0xfe
exit status 2
'go run ./listboxCrash.go' time: 4:07.54s, cpu: 103%
```
</details>

**Comment by adrianboyko** [comment]
Hi @ryanerwin , thanks for trying my code. The problem originally appeared in a "normal" application I was working on but only very infrequently. So I wrote this stress test to see if I could more reliably reproduce the problem. I'm willing to bet that the equivalent C program would not crash -- my inexpert guess is that there is probably a race condition in gotk3's glue between the Go garbage collector and the GObject system.

**Comment by nwg-piotr** [comment]
I noticed a similar error while adding multiple instances of `FileChooserButton`. I replaced them with a `Button` connected to `FileChooserDialog`, and it works with no crashes and much faster.
