### ISSUE TITLE
[Project question] How to implement a custom widget?

### ISSUE THREAD

**Issue by jcbritobr** [gotk3/gotk3#722]
Hello. Im searching by the issues and internet, and could not find an example on how to implement a custom widget using gotk3. I already had found some c implementations, but seems is a different aproach in gotk. May someone help?

**Comment by Grunaka** [comment]
Hi jcbritobr,

I am quite new to the project, but I will try to help you. I my case I try to implement a composite widget. This widget will display the datetime and allow to modify it. I think that composite and custom widgets are different,  but they share similarities.

````go
type WidgetDatetime struct {
    widget gtk.Widget

    time time.Time

    win *gtk.Window

    year *gtk.SpinButton
    month *gtk.ComboBoxText
    day *gtk.SpinButton

    hour *gtk.SpinButton
    minute *gtk.SpinButton
    second *gtk.SpinButton
}
````

In GO we cannot inherit like in C so we need to define a type that wrap the underlying type in our case gtk.Widget or any other type. Now for composite widget I am stuck because I need some binding function that are missing (I am working on it). You can look at some gotk3 internal binding like gtk/label.go. You will see that the GO type Label inherit from a gtk.Widget. They use a bunch of function to wrap/unwrap the widget.

This all the information I have. I hope it can help you.

**Comment by jcbritobr** [comment]
Hello @Grunaka . Thank you very much for the help. I was trying to create a chart. There is a way to embbed the gtk.Widget or, use only gtk.Widget to compose the chart?

**Comment by jcbritobr** [comment]
I'm doing this aproach:

```go
type chart struct {
	gtk.IWidget
	widget gtk.Widget
}

wg := chart{widget: gtk.Widget{}}

```

but getting this issue: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0xcfa599]

goroutine 1 [running]:
main.(*chart).github.com/gotk3/gotk3/gtk.toWidget(0xc000108060, 0x1bc23e4f790)
        <autogenerated>:1 +0x39
github.com/gotk3/gotk3/gtk.(*Container).Add.func1(0xc000006030, 0xe24720, 0xc000108060)
        C:/Users/jcbri/go/pkg/mod/github.com/gotk3/gotk3@v0.5.2/gtk/gtk.go:3122 +0x54
github.com/gotk3/gotk3/gtk.(*Container).Add(0xc000006030, 0xe24720, 0xc000108060)
        C:/Users/jcbri/go/pkg/mod/github.com/gotk3/gotk3@v0.5.2/gtk/gtk.go:3122 +0x46
main.main()
        C:/Workspace/go/gtk3/main.go:73 +0x42f

**Comment by Grunaka** [comment]
I try to implement a simple example but the binding for gtk_widget_new is missing.
I think we need it if we want to create the custom widget.

Did you implement the function for the IWidget interface?
How do you convert your widget to pointer?

````go
type IWidget interface {                                                                                                       
         toWidget() *C.GtkWidget                                                     
         ToWidget() *Widget                                                          
         Set(string, interface{}) error                                              
}
````

**Comment by jcbritobr** [comment]
Hello,
I did not implemented IWidget. I didn't knew how to implement this methods. Then I tryed to embbed Widget in the struct.

**Comment by Grunaka** [comment]
Hi @jcbritobr,

Sorry about the delay.
I tried to implement custom widget multiple time but I failed each time.
Like I said before I don't have a lot of experience with gotk3.
I don't even know if this is possible.
I took a look at gtk3 and we need to call the macro G_DEFINE_TYPE to register a new type.
I have no idea how we can do that with gotk3 sorry.
I will keep looking because I also need this functionality to refactor my application.

````c
G_DEFINE_TYPE (MyButton, my_button, GTK_TYPE_BUTTON)
````

**Comment by jcbritobr** [comment]
I'm too. Tried a lot o times. :(

**Comment by pekim** [comment]
What aspects of a widget do you want to customise? If you just need to implement your own drawing, then [GtkDrawingArea](https://developer.gnome.org/gtk3/stable/GtkDrawingArea.html) may suffice. You would need to handle the [draw](https://developer.gnome.org/gtk3/stable/GtkWidget.html#GtkWidget-draw) signal.

**Comment by jcbritobr** [comment]
> 
> 
> What aspects of a widget do you want to customise? If you just need to implement your own drawing, then [GtkDrawingArea](https://developer.gnome.org/gtk3/stable/GtkDrawingArea.html) may suffice. You would need to handle the [draw](https://developer.gnome.org/gtk3/stable/GtkWidget.html#GtkWidget-draw) signal.

Hello @pekim . Good morning and thanks for the help. I was trying to implement a chart, and some custom signals int it. Its possiblle to get these functionalities?

**Comment by pekim** [comment]
The chart, probably yes if you can draw it on a cairo context. But the custom signals, no.
