### ISSUE TITLE
[BUG] gdk.PixBufGetFormats() panics due to an incorrect type assertion

### ISSUE THREAD

**Issue by awused** [gotk3/gotk3#791]
**Describe the bug**

Calling gdk.PixbufGetFormats() panics due to an incorrect type assertion.

**To Reproduce**

Call gdk.PixbufGetFormats().

**Error messages**

```
panic: interface conversion: interface {} is unsafe.Pointer, not *gdk._Ctype_struct__GdkPixbufFormat

goroutine 1 [running]:
github.com/gotk3/gotk3/gdk.PixbufGetFormats.func1(0x9b7440, 0x39d6e40)
	/storage/cache/go/pkg/mod/github.com/gotk3/gotk3@v0.6.0/gdk/pixbuf_since_2_2.go:47 +0x130
github.com/gotk3/gotk3/glib.(*SList).Foreach(0xc0000fbae0, 0xc0000fbaf0)
	/storage/cache/go/pkg/mod/github.com/gotk3/gotk3@v0.6.0/glib/slist.go:121 +0x5a
github.com/gotk3/gotk3/gdk.PixbufGetFormats(0x0, 0x0, 0x0)
	/storage/cache/go/pkg/mod/github.com/gotk3/gotk3@v0.6.0/gdk/pixbuf_since_2_2.go:46 +0x12c
```

**Environment:**
gtk3 version: 3.24.29-1.fc33 
go version: 1.16
os: Fedora 33
 
**Additional context**

The line `ret = append(ret, &gdk.PixbufFormat{item.(*C.GdkPixbufFormat)})` should be `ret = append(ret, &gdk.PixbufFormat{(*C.GdkPixbufFormat)(item.(unsafe.Pointer))})`. I'm able to work around the problem for now with similar code.

**Comment by hfmrow** [comment]
Hi, https://github.com/gotk3/gotk3/pull/795

**Comment by MJacred** [comment]
@andre-hub: could you close this issue please, as this was fixed with GOTK3 Version 0.6.1?
