### ISSUE TITLE
[BUG] Invalid type function 'webkit_web_view_get_type'

### ISSUE THREAD

**Issue by decentral1se** [gotk3/gotk3#925]
**Describe the bug**

Using `WebkietWebView` in a loaded `.glade` file gives the following error:

```
(project:15232): Gtk-ERROR **: 13:33:38.831: failed to add UI: ui/project.glade:270:1 Invalid type function 'webkit_web_view_get_type'
SIGTRAP: trace trap
PC=0x7f903a8477c7 m=0 sigcode=128
signal arrived during cgo execution
```

(Full stack trace below)

**To Reproduce**
- Use a `WebkietWebView` widget in a `.glade` file
- Load the glade file and compile the program

**Expected behavior**
It works.

**Error messages**

> (project:15232): Gtk-ERROR **: 13:33:38.831: failed to add UI: ui/project.glade:270:1 Invalid type function 'webkit_web_view_get_type'
> SIGTRAP: trace trap
> PC=0x7f903a8477c7 m=0 sigcode=128
> signal arrived during cgo execution
> 
> goroutine 1 [syscall, locked to thread]:
> runtime.cgocall(0x81c1f0, 0xc0001a70e0)
> 	/usr/local/go/src/runtime/cgocall.go:157 +0x4b fp=0xc0001a70b8 sp=0xc0001a7080 pc=0x489c2b
> github.com/gotk3/gotk3/gtk._Cfunc_gtk_builder_new_from_file(0x28f07e0)
> 	_cgo_gotypes.go:6256 +0x48 fp=0xc0001a70e0 sp=0xc0001a70b8 pc=0x578c88
> github.com/gotk3/gotk3/gtk.BuilderNewFromFile({0x97cdb4?, 0xc00010ea00?})
> 	/home/d/go/pkg/mod/github.com/gotk3/gotk3@v0.6.3/gtk/gtk_since_3_10.go:876 +0x67 fp=0xc0001a7140 sp=0xc0001a70e0 pc=0x58df47
> main.main.func1()
> 	/home/d/work/varia/hni/project-desktop/cmd/project/main.go:34 +0x2e fp=0xc0001a71c8 sp=0xc0001a7140 pc=0x808b6e
> runtime.call16(0xc0001d62d0, 0xc0001b01d0, 0x0, 0x0, 0x0, 0x0, 0xc0001a7718)
> 	/usr/local/go/src/runtime/asm_amd64.s:747 +0x43 fp=0xc0001a71e8 sp=0xc0001a71c8 pc=0x4eb003
> runtime.reflectcall(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
> 	<autogenerated>:1 +0x36 fp=0xc0001a7228 sp=0xc0001a71e8 pc=0x4ef2b6
> reflect.Value.call({0x863ce0?, 0xc0001b01d0?, 0x0?}, {0x978b93, 0x4}, {0xd17880, 0x0, 0x886800?})
> 	/usr/local/go/src/reflect/value.go:596 +0xce7 fp=0xc0001a7838 sp=0xc0001a7228 pc=0x512be7
> reflect.Value.Call({0x863ce0?, 0xc0001b01d0?, 0x26e3510?}, {0xd17880?, 0x100000000000c?, 0x1c?})
> 	/usr/local/go/src/reflect/value.go:380 +0xb9 fp=0xc0001a78b0 sp=0xc0001a7838 pc=0x511e39
> github.com/gotk3/gotk3/glib.goMarshal(0x49a588?, 0x0, 0x1, 0x7ffe97bdf190, 0xc0001a7be8?, 0x4927c5?)
> 	/home/d/go/pkg/mod/github.com/gotk3/gotk3@v0.6.3/glib/glib.go:271 +0xa11 fp=0xc0001a7b60 sp=0xc0001a78b0 pc=0x56df11
> _cgoexp_75ce697d4a8b_goMarshal(0x30?)
> 	_cgo_gotypes.go:6414 +0x2c fp=0xc0001a7ba0 sp=0xc0001a7b60 pc=0x571b4c
> runtime.cgocallbackg1(0x571b20, 0xc0001a7cc0?, 0x0)
> 	/usr/local/go/src/runtime/cgocall.go:329 +0x2c2 fp=0xc0001a7c70 sp=0xc0001a7ba0 pc=0x48a122
> runtime.cgocallbackg(0x4c55bc?, 0xc0000061a0?, 0x300000002?)
> 	/usr/local/go/src/runtime/cgocall.go:245 +0x109 fp=0xc0001a7d00 sp=0xc0001a7c70 pc=0x489dc9
> runtime.cgocallbackg(0x571b20, 0x7ffe97bdef90, 0x0)
> 	<autogenerated>:1 +0x29 fp=0xc0001a7d28 sp=0xc0001a7d00 pc=0x4eeec9
> runtime.cgocallback(0xc0001a7d88, 0x489c55, 0x8095d0)
> 	/usr/local/go/src/runtime/asm_amd64.s:1035 +0xcc fp=0xc0001a7d50 sp=0xc0001a7d28 pc=0x4ec84c
> runtime.systemstack_switch()
> 	/usr/local/go/src/runtime/asm_amd64.s:474 +0x8 fp=0xc0001a7d60 sp=0xc0001a7d50 pc=0x4eaac8
> runtime.cgocall(0x8095d0, 0xc0001a7dc0)
> 	/usr/local/go/src/runtime/cgocall.go:175 +0x75 fp=0xc0001a7d98 sp=0xc0001a7d60 pc=0x489c55
> github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x26e00f0, 0x1, 0x26dc170)
> 	_cgo_gotypes.go:1571 +0x4b fp=0xc0001a7dc0 sp=0xc0001a7d98 pc=0x5699ab
> github.com/gotk3/gotk3/glib.(*Application).Run.func4(0xc0001b0230?, {0xc0000240a0?, 0x1, 0x50?}, 0x6?)
> 	/home/d/go/pkg/mod/github.com/gotk3/gotk3@v0.6.3/glib/application.go:185 +0x74 fp=0xc0001a7e00 sp=0xc0001a7dc0 pc=0x56c394
> github.com/gotk3/gotk3/glib.(*Application).Run(0x97dc92?, {0xc0000240a0?, 0x1, 0x1})
> 	/home/d/go/pkg/mod/github.com/gotk3/gotk3@v0.6.3/glib/application.go:185 +0x1b9 fp=0xc0001a7ed0 sp=0xc0001a7e00 pc=0x56c2b9
> main.main()
> 	/home/d/work/varia/hni/project-desktop/cmd/project/main.go:148 +0x1e8 fp=0xc0001a7f40 sp=0xc0001a7ed0 pc=0x807be8
> runtime.main()
> 	/usr/local/go/src/runtime/proc.go:267 +0x2bb fp=0xc0001a7fe0 sp=0xc0001a7f40 pc=0x4bdc7b
> runtime.goexit()
> 	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0001a7fe8 sp=0xc0001a7fe0 pc=0x4ecaa1
> 
> goroutine 2 [force gc (idle)]:
> runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
> 	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00004cfa8 sp=0xc00004cf88 pc=0x4be0ce
> runtime.goparkunlock(...)
> 	/usr/local/go/src/runtime/proc.go:404
> runtime.forcegchelper()
> 	/usr/local/go/src/runtime/proc.go:322 +0xb3 fp=0xc00004cfe0 sp=0xc00004cfa8 pc=0x4bdf53
> runtime.goexit()
> 	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00004cfe8 sp=0xc00004cfe0 pc=0x4ecaa1
> created by runtime.init.6 in goroutine 1
> 	/usr/local/go/src/runtime/proc.go:310 +0x1a
> 
> goroutine 3 [GC sweep wait]:
> runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
> 	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00004d778 sp=0xc00004d758 pc=0x4be0ce
> runtime.goparkunlock(...)
> 	/usr/local/go/src/runtime/proc.go:404
> runtime.bgsweep(0x0?)
> 	/usr/local/go/src/runtime/mgcsweep.go:280 +0x94 fp=0xc00004d7c8 sp=0xc00004d778 pc=0x4a9fb4
> runtime.gcenable.func1()
> 	/usr/local/go/src/runtime/mgc.go:200 +0x25 fp=0xc00004d7e0 sp=0xc00004d7c8 pc=0x49f145
> runtime.goexit()
> 	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00004d7e8 sp=0xc00004d7e0 pc=0x4ecaa1
> created by runtime.gcenable in goroutine 1
> 	/usr/local/go/src/runtime/mgc.go:200 +0x66
> 
> goroutine 4 [GC scavenge wait]:
> runtime.gopark(0xc000074000?, 0xa14038?, 0x1?, 0x0?, 0xc0000071e0?)
> 	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00004df70 sp=0xc00004df50 pc=0x4be0ce
> runtime.goparkunlock(...)
> 	/usr/local/go/src/runtime/proc.go:404
> runtime.(*scavengerState).park(0xce84a0)
> 	/usr/local/go/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc00004dfa0 sp=0xc00004df70 pc=0x4a7849
> runtime.bgscavenge(0x0?)
> 	/usr/local/go/src/runtime/mgcscavenge.go:653 +0x3c fp=0xc00004dfc8 sp=0xc00004dfa0 pc=0x4a7ddc
> runtime.gcenable.func2()
> 	/usr/local/go/src/runtime/mgc.go:201 +0x25 fp=0xc00004dfe0 sp=0xc00004dfc8 pc=0x49f0e5
> runtime.goexit()
> 	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00004dfe8 sp=0xc00004dfe0 pc=0x4ecaa1
> created by runtime.gcenable in goroutine 1
> 	/usr/local/go/src/runtime/mgc.go:201 +0xa5
> 
> goroutine 5 [finalizer wait]:
> runtime.gopark(0x927220?, 0x1004bf201?, 0x0?, 0x0?, 0x4c6285?)
> 	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00004c628 sp=0xc00004c608 pc=0x4be0ce
> runtime.runfinq()
> 	/usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc00004c7e0 sp=0xc00004c628 pc=0x49e1c7
> runtime.goexit()
> 	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00004c7e8 sp=0xc00004c7e0 pc=0x4ecaa1
> created by runtime.createfing in goroutine 1
> 	/usr/local/go/src/runtime/mfinal.go:163 +0x3d
> 
> rax    0x0
> rbx    0x1
> rcx    0x10
> rdx    0x28dd
> rdi    0x0
> rsi    0x1
> rbp    0x7ffe97bde8f0
> rsp    0x7ffe97bde850
> r8     0x7
> r9     0x28ddb00
> r10    0x7cc37593d49e3617
> r11    0x293
> r12    0x6
> r13    0x0
> r14    0x7f903a920ca0
> r15    0x7f903a920cf8
> rip    0x7f903a8477c7
> rflags 0x202
> cs     0x33
> fs     0x0
> gs     0x0
> exit status 2
> make: *** [makefile:11: run] Error 1

**Environment:**
gtk3 version: v0.6.3
go version: 1.21
os: debian latest
 
**Additional context**

N/A

**Comment by decentral1se** [comment]
Really very unsure of what I'm doing but pulling in https://github.com/andre-hub/go-webkit2 made this error go away. I am not quite sure if things are working but will try to get a bit further now...
